language: csharp
solution: SolutionSnapshotter.sln

deploy:
  api_key:
    secure: TX/fh/n8eaEWhMVK8R/3FtTxbU/VCmWUJhN8rpU9nP7bdbFuKgr4NEnXqqmX9INA+ptCptarmr4NkuEQP4+WwSLo04QX1PF+TIWVX+YyIa/t8EQoDgg/Lmc9ZUHT6lEORs/ID2CDPamWoZFOkOa9A6E2nTqkOfEICencCZ8U+e9XvuVNXk1y22VSYMyNMnaD4Vwt7UcH6D+cWI8Tu/jNGF75l1VwYjKOc2OKbJjdOrb7zjNVOHIisczacOfL+b15Wsd6gonuE/M4xeqxFuek3RHNBfe+Alws8tIaKtNwG7WQdgOkSOREmNz6tzjOv3GGXgFRzW0WCjUfe2mqywm53WTsj5qLxVTdyZadONgSpLjcx3xvrmctMZWUYhzLkgdwRZLnyX2+HJCTnVwN93EJWC1BvCoMHBGZr2hg1VXP4rcmwgfUHY2anVvXPSQeUVrjWVC7apPVEz6GMRZkB4mqmxgsO6cu8R3OGdf4dB+kUxXJSEijVBXEjnjvI5mlzg4+M576G3wMIQtUJXEz2KPdLeyOTrrQekJJ4a+21WQWWl/22h/HMavodRWsFsOYIEo3jjQyDR4mZi1/u7KO9vLBcApuwXX4bmq5jR9GRBewPWMBpJp6DKJAK4daUMUjZzgYKhumr3ISGcI4D9Acq0dPnhMwTEAOO6iYCW8IIoWtpTk=
  draft: true
  file: SolutionSnapshotter\bin\Debug\net472\win7-x64\solution-snapshotter.exe
  provider: releases
  skip_cleanup: true
  true:
    tags: true
