# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: "windows-2019"

steps:
  - task: NuGetToolInstaller@1
    inputs:
      versionSpec: 
    displayName: "Install NuGet"

  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: 'SolutionSnapshotter.sln'
      feedsToUse: 'select'
    displayName: "Restore packages"

  - task: MSBuild@1
    inputs:
      solution: "SolutionSnapshotter.sln"
      configuration: Release
      msbuildVersion: "latest"
    displayName: "Build"
