# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: "windows-2019"

variables:
  agentBuildDir: $(System.DefaultWorkingDirectory)

steps:
  - task: NuGetToolInstaller@1
    inputs:
      versionSpec:
    displayName: "Install NuGet"

  - task: NuGetCommand@2
    inputs:
      command: "restore"
      restoreSolution: "SolutionSnapshotter.sln"
      feedsToUse: "select"
    displayName: "Restore packages"

  - task: MSBuild@1
    inputs:
      solution: "SolutionSnapshotter.sln"
      configuration: Release
      msbuildVersion: "latest"
    displayName: "Build"

  - task: VisualStudioTestPlatformInstaller@1
    inputs:
      packageFeedSelector: "nugetOrg"
      versionSelector: "latestPreRelease"
    displayName: "Install tests platform"

  - task: VSTest@2
    inputs:
      testSelector: "testAssemblies"
      testAssemblyVer2: |
        **\*Tests.dll
        **\*test*.dll
        !**\*TestAdapter.dll
        !**\obj\**
      searchFolder: "$(System.DefaultWorkingDirectory)"
    displayName: "Run tests"
